require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bootstrap4jekyll.gemspec'
    -
RSpec/NestedGroups:
  Max: 4

Layout/LineLength:
  Max: 122

Metrics/MethodLength:
  Max: 16


Metrics/ModuleLength:
   Enabled: false

Style/DocumentationMethod:
  Description: 'Public methods.'
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

